import { page, prose, question, made, blot, clear, shots, hits, escapes, prime, board } from '../lib/kit.mjs';
import { board as pos } from '../lib/board.mjs';

export default page('Blitz', [

  prose`**A [[blitz]] is an attack on his loose checkers.** You hit, and you make the
    point you hit on, so he has nothing to come back to. Each of these rolls
    does both — find the play that does.`,

  question({
    id: 'bz-1',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x...o.||o.....
......||o.....
--------------
......||......
o.....||x.....
o.....||xx....
o..xx.||xx....
o..xx.||xx.o..
bar o1`,
    dice: [6, 5],
    ask: prose`He is on the [[bar]] and there is a checker of his on the 3 point.`,
    goals: [
      hits(3, prose`You hit, and he has two checkers to bring back.`, prose`There is a [[blot]] of his on the 3 point.`),
      made(3, prose`The 3 point is yours as well — three points made in your [[home board]] now.`, prose`Hitting is only half of it. Cover, and the point is yours.`),
    ],
  }),

  question({
    id: 'bz-2',
    board: pos`
x...o.||o.....
x...o.||o.....
....o.||o.....
......||o.....
......||o.....
--------------
......||......
o.....||x.....
o...x.||x.....
oxxxx.||x...o.
oxxxx.||x.o.o.`,
    dice: [6, 2],
    ask: prose`A checker of his sitting on your 4 point.`,
    goals: [
      hits(4, prose`Off he goes.`, prose`He has a [[blot]] on your 4 point and you can reach it.`),
      made(4, prose`And the 4 point is made behind him.`, prose`Hit and cover in the same roll — you have the checkers for it.`),
    ],
  }),

  question({
    id: 'bz-3',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
....o.||o.....
......||o.....
--------------
......||......
o.....||x.....
o...x.||x.x...
ox..x.||x.x...
ox..x.||x.x.o.
bar o1`,
    dice: [4, 2],
    ask: prose`He is on the [[bar]] with a straggler on your 2 point.`,
    goals: [
      hits(2, prose`He is on the bar twice over.`, prose`There is a checker of his on the 2 point.`),
      made(2, prose`The 2 point is deep, and while he is dancing it is worth having.`, prose`Make the point while you hit. A loose checker there will just be hit back.`),
    ],
    antigoals: [
      made(9, prose`The 9 point is a good point and it is not urgent. He is on the [[bar]] with a checker loose; that is urgent.`),
    ],
  }),

  question({
    id: 'bz-4',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x...o.||o.....
......||o.....
--------------
......||......
o.....||......
o...x.||xx....
o..xx.||xx....
o..xx.||xxo...
bar o1`,
    dice: [4, 2],
    ask: prose`He is on the [[bar]], and his other checker is on your 4 point.`,
    goals: [
      hits(4, prose`Hit.`, prose`He is on your 4 point.`),
      made(4, prose`The [[golden point]]\u2019s neighbour, made, with him on the bar and two checkers to bring in.`, prose`Hitting loose leaves him a target to come back to. Cover it.`),
    ],
  }),

  question({
    id: 'bz-5',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x...o.||o.....
......||o.....
--------------
......||......
o.....||......
o...x.||xx....
o..xx.||xx....
o..xx.||xxo...
bar o1`,
    dice: [2, 1],
    ask: prose`The smallest roll, and the best use of it is close to home.`,
    goals: [
      hits(4, prose`You hit,`, prose`He has a checker on your 4 point.`),
      made(4, prose`and the 4 point is made. Three points in your [[home board]] and two of his checkers to bring in past them.`, prose`One checker on the 4 point is not a point. Cover it.`),
    ],
    antigoals: [
      made(7, prose`The [[bar point]] is a fine point and it is not the one that matters. He is on the bar; keep him there.`),
    ],
  }),

  question({
    id: 'bz-6',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
......||o.....
......||o.....
--------------
......||......
o.....||x.....
o...x.||x.x...
ox..x.||x.x...
ox..x.||xox..o
bar o1`,
    dice: [6, 1],
    ask: prose`He is on the [[bar]], with a checker on your [[golden point]].`,
    goals: [
      hits(5, prose`The 5 point, hit.`, prose`He is standing on the best point on the board.`),
      made(5, prose`And made. He is on the bar looking at three of your points.`, prose`Hit and cover. The 5 point is worth both checkers.`),
    ],
    antigoals: [
      made(7, prose`The [[bar point]] would be right in almost any quiet position. This one is not quiet.`),
    ],
  }),

  question({
    id: 'bz-7',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
....o.||o.....
......||o.....
--------------
......||......
o.....||x.....
o...x.||x.x...
ox..x.||x.x...
ox..x.||x.x.o.
bar o1`,
    dice: [6, 4],
    ask: prose`On the [[bar]] again, and a checker of his on your 2 point.`,
    goals: [
      hits(2, prose`Hit it.`, prose`There is a checker of his on the 2 point.`),
      made(2, prose`Deep, and worth it: he now has two on the bar and three of your points closed.`, prose`Cover, or you have simply given him something to hit.`),
    ],
    antigoals: [
      made(7, prose`Building the [[bar point]] is the patient play, and he is not giving you time to be patient.`),
    ],
  }),

  question({
    id: 'bz-8',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x...o.||o.....
......||o.....
--------------
......||......
o.....||x.....
o.....||xx....
o..xx.||xx....
o..xx.||xx.o..
bar o1`,
    dice: [3, 2],
    ask: prose`Small numbers, and he is on the [[bar]].`,
    goals: [
      hits(3, prose`Hit,`, prose`There is a checker of his on the 3 point.`),
      made(3, prose`and covered. Three points made and two of his checkers to come back through them.`, prose`A lone checker on the 3 point is a gift. Make the point.`),
    ],
  }),

  question({
    id: 'bz-9',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
....o.||o.....
......||o.....
--------------
......||......
o.....||......
o...x.||x.....
o.x.x.||xxx...
o.x.x.||xxxo..
bar o1`,
    dice: [5, 3],
    ask: prose`He is on the [[bar]] and your board is nearly closed.`,
    goals: [
      hits(3, prose`Hit.`, prose`He has a [[blot]] on the 3 point.`),
      made(3, prose`Four points in your [[home board]], four in a row, and two of his checkers on the [[bar]]. That is a [[blitz]].`, prose`Hit and cover — the fourth point is worth more than anything else on the board.`),
    ],
  }),

  question({
    id: 'bz-10',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x...o.||o.....
......||o.....
--------------
......||......
o.....||x.....
o.....||xx....
o..xx.||xx....
o..xx.||xx.o..
bar o1`,
    dice: [6, 2],
    ask: prose`One more.`,
    goals: [
      hits(3, prose`Hit,`, prose`There is a checker of his on the 3 point.`),
      made(3, prose`and cover. He has two to bring in and three points to get past.`, prose`Cover it. A [[blot]] on the 3 point invites him straight back.`),
    ],
    antigoals: [
      made(7, prose`The [[bar point]] can wait. He cannot.`),
    ],
  }),

  prose`That is a blitz. Next, the other way to play.`,
], { next: 'blitz_or_prime' });
