import { page, prose, question, made, blot, clear, shots, hits, escapes, prime, board } from '../lib/kit.mjs';
import { board as pos } from '../lib/board.mjs';

export default page('Blitz or prime', [

  prose`**Both plans are on the board now.** Look at his back checkers before you
    move: loose checkers can be attacked, an [[anchor]] cannot.`,

  question({
    id: 'bp-1',
    board: pos`
x...o.||o....x
x...o.||o....x
x...o.||o.....
x.....||o.....
x.....||o.....
--------------
o.....||x.....
o.....||x.....
o...x.||x.....
o...x.||x.....
o...x.||xo....
bar o1`,
    dice: [3, 1],
    ask: prose`He is on the [[bar]], with a checker on your 5 point.`,
    goals: [
      hits(5, prose`Hit,`, prose`He is standing on your 5 point.`),
      made(5, prose`and made. The best point on the board, and he is looking at it from the bar.`, prose`Cover it. Hitting and leaving a [[blot]] there is the worst of both.`),
    ],
  }),

  question({
    id: 'bp-2',
    board: pos`
x...o.||o.....
x...o.||o.....
....o.||o.....
......||o.....
......||o.....
--------------
......||......
o.....||x.....
o...x.||x.....
oxxxx.||x...o.
oxxxx.||x.o.o.`,
    dice: [6, 3],
    ask: prose`He is [[anchor|anchored]] on your 2 point.`,
    goals: [
      made(5, prose`The 5 point. Nothing to attack, so build in front of him.`, prose`Against an [[anchor]], the 5 point is the play.`),
    ],
  }),

  question({
    id: 'bp-3',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
....o.||o.....
......||o.....
--------------
......||......
o.....||......
o...x.||x.....
o..xxx||x.x...
o..xxx||x.x.o.
bar o1`,
    dice: [6, 5],
    ask: prose`On the [[bar]], and a checker of his deep in your board.`,
    goals: [
      hits(2, prose`Hit him again.`, prose`There is a [[blot]] of his on the 2 point.`),
      made(2, prose`Deep, but he is on the bar and every point counts.`, prose`Cover, or he comes straight back to it.`),
    ],
  }),

  question({
    id: 'bp-4',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
....o.||o.....
......||o.....
--------------
......||......
o.....||x.....
o...x.||x.x...
ox..x.||x.x...
ox..x.||x.x.o.
bar o1`,
    dice: [6, 3],
    ask: prose`He is on the [[bar]] — but look at what the roll can build.`,
    goals: [
      made(5, prose`The 5 point. Nothing of his is loose enough to attack, so take the point that blocks him.`, prose`The 5 point is yours for the taking.`),
      prime(3),
    ],
  }),

  question({
    id: 'bp-5',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
......||o.....
......||o.....
--------------
o.....||......
o.....||x.....
o...x.||xx....
o.x.x.||xx....
o.x.x.||xx.o..
bar o1`,
    dice: [5, 3],
    ask: prose`A checker of his on your 3 point, and he is on the [[bar]].`,
    goals: [
      hits(3, prose`Hit,`, prose`He has a [[blot]] on the 3 point.`),
      made(3, prose`and cover. Three home board points with two of his checkers to bring back.`, prose`Half a job. Cover the point.`),
    ],
  }),

  question({
    id: 'bp-6',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
......||o.....
......||o.....
--------------
......||......
......||x.....
o...x.||x....o
ox.xx.||x....o
oxoxx.||xx...o`,
    dice: [5, 2],
    ask: prose`Three of his checkers are [[anchor|anchored]] on your 1 point.`,
    goals: [
      made(3, prose`The 3 point. He is not coming back through anything, so build where it blocks.`, prose`You can make the 3 point.`),
      shots(0, prose`Nothing loose.`, prose`You left a [[blot]] within his reach.`),
    ],
  }),

  question({
    id: 'bp-7',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x.....||o.....
......||o.....
--------------
o.....||......
o.....||x.....
o...x.||x.....
o.x.x.||xx....
o.x.x.||xxo...
bar o1`,
    dice: [4, 2],
    ask: prose`On the [[bar]], with a checker on your 4 point.`,
    goals: [
      hits(4, prose`Hit,`, prose`His checker is on your 4 point.`),
      made(4, prose`and made. Three in a row now, and two of his to come back through them.`, prose`Cover it.`),
    ],
  }),

  question({
    id: 'bp-8',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x.....||o.....
......||o.....
--------------
......||......
o.....||x.....
o...x.||x.....
o.x.x.||x....o
oxx.x.||xxo..o`,
    dice: [4, 3],
    ask: prose`He is [[anchor|anchored]]. There is a hit available and it is not the play.`,
    goals: [
      made(5, prose`The 5 point, in front of an [[anchor]] that cannot move.`, prose`The 5 point is the one that matters.`),
      blot(9, prose`And a [[builder]] on the 9, ready for the [[bar point]].`, prose`The other checker belongs on the 9, where it bears on the points you still want.`),
    ],
    antigoals: [
      hits(4, prose`The hit gains you a few pips and nothing else — his [[anchor]] is what beats you, and hitting a spare does not touch it.`),
    ],
  }),

  question({
    id: 'bp-9',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
......||o.....
......||o.....
--------------
o.....||......
o.....||x.....
o...x.||xx....
o.x.x.||xx....
o.x.x.||xx.o..
bar o1`,
    dice: [3, 2],
    ask: prose`Small numbers, and he is on the [[bar]].`,
    goals: [
      hits(3, prose`Hit,`, prose`There is a checker of his on the 3 point.`),
      made(3, prose`and cover. Keep him out.`, prose`A loose checker on the 3 point will be hit straight back.`),
    ],
  }),

  question({
    id: 'bp-10',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x.....||o.....
......||o.....
--------------
o.....||......
o.....||x.....
o...x.||x.....
o.x.x.||xx....
o.x.x.||xxo...
bar o1`,
    dice: [6, 4],
    ask: prose`The last one.`,
    goals: [
      hits(4, prose`Hit,`, prose`He has a [[blot]] on your 4 point.`),
      made(4, prose`and cover: 4, 5, 6 made, and him on the [[bar]] behind all of it.`, prose`Cover the point.`),
    ],
  }),

  prose`Loose, attack. Anchored, build.`,
], { next: 'duplication' });
