import { page, prose, question, made, blot, clear, shots, numbers, hits, escapes, prime, board } from '../lib/kit.mjs';
import { board as pos } from '../lib/board.mjs';

export default page('Duplication', [

  prose`**Sometimes every play leaves two [[blot|blots]]. Leave them behind the same
    number.** Two blots he hits with 3s is one shot. Two blots he hits with 3s
    and 5s is two, and he is twice as likely to get you.`,

  question({
    id: 'dup-97',
    board: pos`
.x.xo.||o.....
.x..o.||o.....
.x..o.||o.....
....o.||o.....
......||o.....
--------------
......||......
.o....||......
xo....||...x..
xo....||..xx.o
xox...||xxxx.o`,
    dice: [3, 2],
    ask: prose`Nothing here can be played safe.`,
    goals: [
      numbers(1, prose`Both blots sit behind the same number. Only 5s hit you, and
        that is eleven rolls out of thirty-six rather than twice as many.`),
      made(5),
    ],
  }),

  question({
    id: 'dup-81',
    board: pos`
xx.xo.||o.....
x..xo.||o.....
x..xo.||o.....
....o.||o.....
......||o.....
--------------
......||......
o.....||......
o.....||......
o....x||xx...o
o....x||xxxx.o`,
    dice: [6, 3],
    ask: prose`Whatever you do, two checkers are left out.`,
    goals: [
      numbers(1, prose`Both blots sit behind the same number. Only 2s hit you, and
        that is eleven rolls out of thirty-six rather than twice as many.`),
    ],
  }),

  question({
    id: 'dup-5',
    board: pos`
.xxxo.||o.....
..xxo.||o.....
....o.||o.....
......||o.....
......||o.....
--------------
......||......
o.....||......
oxx...||.....o
oxx...||.x...o
oxx...||.xxx.o`,
    dice: [4, 2],
    ask: prose`One checker is short of the wall and one is short of home.`,
    goals: [
      numbers(1, prose`Both blots sit behind the same number. Only 2s hit you, and
        that is eleven rolls out of thirty-six rather than twice as many.`),
    ],
  }),

  question({
    id: 'dup-76',
    board: pos`
.x.xo.||o.....
...xo.||o.....
...xo.||o.....
....o.||o.....
......||o.....
--------------
......||......
.o....||......
.o....||......
.oxx..||.x.x.o
xoxx.x||.xxx.o`,
    dice: [6, 1],
    ask: prose`Two blots, and a choice of where to put them.`,
    goals: [
      numbers(1, prose`Both blots sit behind the same number. Only 3s hit you, and
        that is eleven rolls out of thirty-six rather than twice as many.`),
    ],
  }),

  question({
    id: 'dup-17',
    board: pos`
x.x.o.||o.....
x.x.o.||o.....
....o.||o.....
....o.||o.....
......||o.....
--------------
......||......
o.....||......
o.....||x.....
o.x..x||xx..o.
o.x..x||xxxxo.`,
    dice: [5, 4],
    ask: prose`A long way to bring one checker.`,
    goals: [
      numbers(1, prose`Both blots sit behind the same number. Only 1s hit you, and
        that is eleven rolls out of thirty-six rather than twice as many.`),
    ],
  }),

  question({
    id: 'dup-71',
    board: pos`
xxxxo.||o.....
xx..o.||o.....
....o.||o.....
....o.||o.....
......||o.....
--------------
......||......
o.....||......
o.....||x.....
o.x...||x.x..o
o.x...||xxxx.o`,
    dice: [4, 3],
    ask: prose`You cannot cover everything.`,
    goals: [
      numbers(1, prose`Both blots sit behind the same number. Only 4s hit you, and
        that is eleven rolls out of thirty-six rather than twice as many.`),
    ],
  }),

  question({
    id: 'dup-57',
    board: pos`
ox..o.||o.....
o...o.||o.....
o...o.||o.....
o.....||o.....
......||o.....
......||o.....
--------------
......||......
......||......
......||......
x....x||.x....
x....x||.x..o.
x..xxx||xxxxo.`,
    dice: [4, 1],
    ask: prose`Small numbers, and no safe home for either of them.`,
    goals: [
      numbers(1, prose`Both blots sit behind the same number. Only 1s hit you, and
        that is eleven rolls out of thirty-six rather than twice as many.`),
      made(6),
    ],
  }),

  question({
    id: 'dup-8',
    board: pos`
xx.xo.||o.....
.x.xo.||o.....
....o.||o.....
....o.||o.....
......||o.....
--------------
......||......
o.....||......
o.....||......
o.xx.x||x...o.
o.xx.x||x.xxo.`,
    dice: [4, 2],
    ask: prose`Three checkers loose, and only two dice.`,
    goals: [
      numbers(1, prose`Both blots sit behind the same number. Only 1s hit you, and
        that is eleven rolls out of thirty-six rather than twice as many.`),
      made(4),
    ],
  }),

  question({
    id: 'dup-84',
    board: pos`
oxx.o.||o.....
o.x.o.||o.....
o...o.||o.....
o.....||o.....
......||o.....
......||o.....
--------------
......||......
......||......
......||......
...x.x||..x...
...x.x||..x.o.
x..xxx||..xxo.`,
    dice: [3, 2],
    ask: prose`Both numbers want to go to the same place.`,
    goals: [
      numbers(1, prose`Both blots sit behind the same number. Only 1s hit you, and
        that is eleven rolls out of thirty-six rather than twice as many.`),
      made(6),
    ],
  }),

  question({
    id: 'dup-34',
    board: pos`
xxx.o.||o.....
x...o.||o.....
....o.||o.....
....o.||o.....
......||o.....
--------------
......||......
o.....||......
o.x.x.||......
o.x.x.||x...o.
o.x.x.||xxxxo.`,
    dice: [4, 1],
    ask: prose`The last one. Where do the two blots belong?`,
    goals: [
      numbers(1, prose`Both blots sit behind the same number. Only 3s hit you, and
        that is eleven rolls out of thirty-six rather than twice as many.`),
    ],
  }),

  prose`When you cannot be safe, be hit by one number.`,
], { next: 'bearing_off' });
