import { page, prose, question, made, blot, clear, shots, hits, escapes, prime, board } from '../lib/kit.mjs';
import { board as pos } from '../lib/board.mjs';

export default page('Prime', [

  prose`**A [[prime]] is a wall of points side by side.** One point on its own is
    worth something; the same point next to another is worth much more. Every
    roll here can make a point. Make the one that joins up.`,

  question({
    id: 'pr-1',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x.....||o.....
......||o.....
--------------
......||......
o.....||x.....
o...x.||x.....
o.x.x.||x....o
oxx.x.||xxo..o`,
    dice: [4, 2],
    ask: prose`He is [[anchor|anchored]] on your 1 point. Nothing you do will dislodge him.`,
    goals: [
      made(5, prose`The [[golden point]], made. It joins the 6 point, and it is exactly where his back checkers must pass.`, prose`You can make the 5 point, and against an anchor that is worth more than anything else here.`),
    ],
  }),

  question({
    id: 'pr-2',
    board: pos`
x...o.||o....x
x...o.||o....x
x...o.||o.....
x.....||o.....
x.....||o.....
--------------
o.....||x.....
o.....||x.....
o...x.||x.....
o...x.||x.....
o...x.||xo....
bar o1`,
    dice: [6, 6],
    ask: prose`Four sixes.`,
    goals: [
      made(7, prose`The [[bar point]]: 6, 7 and 8 in a row.`, prose`Four sixes will make you the [[bar point]] if you let them.`),
      made(18, prose`And a point in his outfield, with both back checkers safely on it.`, prose`You had sixes to spare. Your back checkers could have used two of them.`),
    ],
  }),

  question({
    id: 'pr-3',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x.....||o.....
......||o.....
--------------
......||......
o.....||......
o...x.||x.....
o.x.xx||x...o.
o.xoxx||xx..o.`,
    dice: [6, 3],
    ask: prose`He is [[anchor|anchored]] on your 2 point, and there is a loose checker of his in your outfield.`,
    goals: [
      made(5, prose`Four points in a row — 5, 6, 7, 8 — right in front of his [[anchor]].`, prose`The 5 point closes the gap in your wall.`),
      shots(0, prose`And nothing of yours can be touched.`, prose`You left something where he can reach it.`),
    ],
  }),

  question({
    id: 'pr-4',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x.....||o.....
......||o.....
--------------
......||......
o.....||......
o...x.||x.....
o..xx.||xx...o
o..xx.||xxx.oo`,
    dice: [6, 3],
    ask: prose`One checker, all the way from the [[mid point]].`,
    goals: [
      made(4, prose`The 4 point, and your wall runs 4, 5, 6.`, prose`You have a [[blot]] on the 4 point and the checkers to cover it.`),
      prime(3, prose`Three in a row in front of an [[anchor]] he cannot leave.`, prose`Points on their own are worth less than points in a row.`),
    ],
  }),

  question({
    id: 'pr-5',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x.....||o.....
......||o.....
--------------
......||......
o.....||x.....
o...x.||x.....
o.x.x.||x....o
oxx.x.||xxo..o`,
    dice: [3, 2],
    ask: prose`Small numbers, and he is not going anywhere.`,
    goals: [
      made(5, prose`The 5 point again. Against an [[anchor]] it is always the point you want.`, prose`The 5 point is there and it is the one that counts.`),
      shots(0, prose`Nothing left loose.`, prose`You left a [[blot]] where his [[anchor]] can reach it.`),
    ],
  }),

  question({
    id: 'pr-6',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
......||o.....
......||o.....
--------------
......||......
o.....||......
o.x.x.||x.....
o.x.xx||x....o
o.x.xx||xx..oo`,
    dice: [6, 2],
    ask: prose`You already hold the 6, 7 and 8.`,
    goals: [
      prime(4, prose`Four in a row. He needs to roll past all of it in one go, and he cannot.`, prose`Three points in a row want to be four. Look at the 5 point.`),
    ],
  }),

  question({
    id: 'pr-7',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x.....||o.....
......||o.....
--------------
......||......
o.....||......
o...x.||x.....
o.x.x.||xx...o
o.xxx.||xx.o.o`,
    dice: [6, 1],
    ask: prose`The [[bar point]] is the gap.`,
    goals: [
      made(7, prose`6, 7, 8, 9 — four in a row, and his back checkers behind all of it.`, prose`The [[bar point]] is open and you have two checkers that reach it.`),
      prime(4),
    ],
    antigoals: [
      hits(3, prose`Hitting is tempting and it gains you almost nothing here — he is [[anchor|anchored]], so he was never going anywhere.`),
    ],
  }),

  question({
    id: 'pr-8',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x.....||o.....
......||o.....
--------------
o.....||......
o.....||x.....
o...x.||x.....
o..xx.||x.x...
o..xx.||x.xo..
bar o1`,
    dice: [3, 1],
    ask: prose`3-1 again, and the answer is the same as it always was.`,
    goals: [
      made(5, prose`The [[golden point]], and 4, 5, 6 in a row behind it.`, prose`The 5 point. It is always the 5 point.`),
      prime(3),
    ],
  }),

  question({
    id: 'pr-9',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x.....||o.....
......||o.....
--------------
......||......
o.....||......
o...x.||x.....
o.x.x.||xx...o
o.xxx.||xx.o.o`,
    dice: [5, 2],
    ask: prose`He is on your 1 point with two checkers and no reason to move.`,
    goals: [
      made(4, prose`The 4 point, joining 5 and 6.`, prose`You can make the 4 point and join up your wall.`),
      prime(3),
    ],
  }),

  question({
    id: 'pr-10',
    board: pos`
x...o.||o.....
x...o.||o.....
x...o.||o.....
x.....||o.....
......||o.....
--------------
o.....||......
o.....||x.....
o...x.||x.....
o..xx.||x.x..o
o..xx.||x.x..o`,
    dice: [6, 2],
    ask: prose`Last one.`,
    goals: [
      made(7, prose`The [[bar point]], and three in a row in front of him.`, prose`The [[bar point]] is the point that matters here.`),
      prime(3),
    ],
    antigoals: [
      made(2, prose`The 2 point is a point, and it is behind him and on its own. A point that joins the wall is worth several that do not.`),
    ],
  }),

  prose`That is a prime. Now the two together, and you choose.`,
], { next: 'blitz_or_prime' });
